GET http://localhost:3000/reservations/ HTTP/1.1

###

POST http://localhost:3000/reservations/ HTTP/1.1
content-type: application/json

{
    "id": null,
    "startDateTime": "Wed, 21 Oct 2015 18:27:50 GMT",
    "endDateTime": "Wed, 21 Oct 2015 18:27:50 GMT",
    "startDate": "05-09-2020",
    "startTime": "12:12",
    "endTime": "14:14",
    "players": 2,
    "isJoined": false
}

###

DELETE http://localhost:3000/reservations/0 HTTP/1.1